<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 * C:\xampp\htdocs\SheaMoisture\app\design\frontend\Venustheme\yume\Magento_Theme\templates\html\footer.phtml
 */
// @codingStandardsIgnoreFile
?>
<div class="footer-container">
    <div class="footer">
        <?php echo $block->getChildHtml() ?>
        <p class="bugs"><?php /* @escapeNotVerified */ echo __('Help Us Keep Magento Healthy') ?> - <a
                href="http://www.magentocommerce.com/bug-tracking"
                target="_blank"><strong><?php /* @escapeNotVerified */ echo __('Report All Bugs') ?></strong></a>
        </p>
        <address><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></address>
    </div>
    <div class="footer_container">           
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sheamoisture_jtf')->toHtml(); ?>	
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sheamoisture_oes')->toHtml(); ?>
        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('sheamoisture_footer_cc')->toHtml(); ?>
    </div>
</div>
